version: "3.7"

services:
    # The Application
    app:
      container_name: app
      build:
        context: ./
        dockerfile: app.dockerfile
      working_dir: /var/www
      volumes:
        - ./:/var/www
      environment:
        CONTAINER_ROLE: app
      depends_on:
        - database
      environment:
        - "DB_PORT=3306"
        - "DB_HOST=database"
    # The Web Server
    web:
        build:
            context: ./
            dockerfile: web.dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - app
        ports:
            - 80:80
    database:
        image: mysql:5.7
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - "33061:3306"
volumes:
    dbdata: